### ISSUE TITLE
I would like to add new code to this project and would like to ask a local development question

### ISSUE THREAD

**Issue by studyduck** [dkapila/Roam-Portal#3]
Here's what I've just done, first download the project locally via git clone
1. npm install
2. npm run build, the packaged result is exported to C:\Users\xxx\Desktop\Roam-Portal\dist directory
3. enable developer mode in roam, then choose to load the plugin from C:\Users\xxx\Desktop\Roam-Portal\dist, finally the plugin is running in roam
The problem I'm having is that whenever I make changes to the code, I need to run 'npm run build' again and then click the 'reload' button in the roam depot settings to see the changes.
How do you develop and modify the code locally? Do you also run 'npm run build' manually every time you make changes to the code?

**Comment by dkapila** [comment]
hi! 

I know this is not the best method, but I've used the Chrome extension version as a faster way previously to work with. Porting it to the Roam Depot was my last work on the extension earlier this year, so I have not put any effort to make the build process easier.

If you can contribute to making the build easier, I would love that, and also open to code suggestions/improvements.

Sorry it's not ideal - since on the whole this extension is in maintenance mode from my side.
